name: Shell commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python commands
        run: |
          print("hello world")
        shell: python    # we need to inform GitHub actions that this scripts runs on python shell not bash