name: first workflow

on:
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: self-hosted
    steps:
      - name: firstjob script
        shell: bash
        run: |

          echo "hi"
  # secondjob:

