name: first workflow

on:
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: self-hosted
    steps:
      - name: firstjob script
        shell: cmd
        run: |

          echo "hi"
  # secondjob:

